version: '3.8'

services:
  api:
    build: .
    container_name: styleai-api
    restart: unless-stopped
    ports:
      - '5001:5001'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./app:/app/app
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
      - ./temp:/app/temp
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5001/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
